// Top ~200 cities of Argentina for autocomplete
export const ARGENTINA_CITIES = [
    "Buenos Aires",
    "CABA",
    "Palermo",
    "Belgrano",
    "Caballito",
    "Villa del Parque",
    "Flores",
    "Almagro",
    "Recoleta",
    "San Telmo",
    "Córdoba",
    "Rosario",
    "La Plata",
    "Mar del Plata",
    "San Miguel de Tucumán",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Santiago del Estero",
    "Corrientes",
    "Neuquén",
    "Bahía Blanca",
    "Posadas",
    "Mendoza",
    "San Salvador de Jujuy",
    "Paraná",
    "Río Cuarto",
    "Santa Rosa",
    "San Luis",
    "Comodoro Rivadavia",
    "Formosa",
    "Concordia",
    "Rawson",
    "Viedma",
    "Ushuaia",
    "Río Gallegos",
    "San Carlos de Bariloche",
    "General Roca",
    "Cipolletti",
    "Trelew",
    "Puerto Madryn",
    "Esquel",
    "Zárate",
    "Campana",
    "Luján",
    "Mercedes",
    "San Nicolás de los Arroyos",
    "Junín",
    "Pergamino",
    "Olavarría",
    "Tandil",
    "Azul",
    "Necochea",
    "Quilmes",
    "Lanús",
    "Lomas de Zamora",
    "Avellaneda",
    "Morón",
    "Tres de Febrero",
    "San Martín",
    "Vicente López",
    "San Isidro",
    "Tigre",
    "Escobar",
    "Pilar",
    "Moreno",
    "Merlo",
    "La Matanza",
    "Ezeiza",
    "Esteban Echeverría",
    "Almirante Brown",
    "Florencio Varela",
    "Berazategui",
    "San Fernando",
    "José C. Paz",
    "Malvinas Argentinas",
    "Hurlingham",
    "Ituzaingó",
    "San Miguel",
    "Villa Maipú",
    "Grand Bourg",
    "Los Polvorines",
    "La Reja",
    "Villa Ballester",
    "González Catán",
    "Temperley",
    "Remedios de Escalada",
    "Adrogué",
    "Monte Grande",
    "Longchamps",
    "Canning",
    "Don Torcuato",
    "Bella Vista",
    "Garín",
    "Pacheco",
    "Boulogne",
    "Martínez",
    "Olivos",
    "Florida",
    "Carapachay",
    "Muñiz",
    "Palpalá",
    "Libertador General San Martín",
    "La Banda",
    "Belén",
    "Villa Mercedes",
    "San Rafael",
    "Godoy Cruz",
    "Guaymallén",
    "Maipú",
    "Las Heras",
    "Luján de Cuyo",
    "Rivadavia",
    "Villa Nueva",
    "Alta Gracia",
    "Villa Carlos Paz",
    "Bell Ville",
    "Villa María",
    "Marcos Juárez",
    "San Francisco",
    "Deán Funes",
    "Cruz del Eje",
    "La Falda",
    "Cosquín",
    "Jesús María",
    "Leones",
    "Rafaela",
    "Reconquista",
    "Venado Tuerto",
    "Esperanza",
    "Gálvez",
    "Cañada de Gómez",
    "El Palomar",
    "Ramos Mejía",
    "Haedo",
    "Castelar",
    "Ituzaingó",
    "Curuguaty",
    "Oberá",
    "El Dorado",
    "Puerto Iguazú",
    "Apóstoles",
    "Paso de los Libres",
    "Goya",
    "Curuzú Cuatiá",
    "Mercedes",
    "Empedrado",
    "Charata",
    "Presidencia Roque Sáenz Peña",
    "Villa Ángela",
    "Clorinda",
    "Pirané",
    "San Pedro",
    "Tartagal",
    "Orán",
    "Metán",
    "General Güemes",
    "Gral. Pico",
    "Santa Rosa",
    "Toay",
    "Río Colorado",
    "Cutral Có",
    "Plaza Huincul",
    "Centenario",
    "Cinco Saltos",
    "Rincón de los Sauces",
    "Zapala",
    "Chos Malal",
    "Caviahue",
    "San Martín de los Andes",
    "Villa La Angostura",
    "El Bolsón",
    "Lago Puelo",
    "Madryn",
    "Gaiman",
    "Dolavon",
    "Rada Tilly",
    "Caleta Olivia",
    "Las Heras",
    "Perito Moreno",
    "Gobernador Gregores",
    "El Calafate",
    "El Chaltén",
    "Río Grande",
    "Tolhuin",
    "Almirante Brown",
];

export function searchCities(query: string, limit = 8): string[] {
    if (!query || query.length < 2) return [];
    const q = query.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return ARGENTINA_CITIES.filter(city => {
        const c = city.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
        return c.startsWith(q) || c.includes(q);
    }).slice(0, limit);
}
